micronaut:
  application:
    name: demo
  server:
    port: 8082
    context-path: /api
netty:
  default:
    allocator:
      max-order: 3


r2dbc:
  datasources:
    default:
      dialect: POSTGRES
      url: "r2dbc:postgresql://localhost:5432/demo-micronaut"
      username: 'postgres'
      password: '123'
      driver: postgresql


flyway:
  datasources:
    default:
      locations: classpath:db/migration

endpoints:
  flyway:
    enabled: true
    sensitive: false